/**
 * PDF Report Generation Service
 * 
 * STATUS: DISABLED - Feature not yet implemented
 * 
 * This service is currently disabled. PDF report generation requires:
 * - Backend API endpoint for PDF generation
 * - PDF generation library (react-native-pdf or similar)
 * 
 * To enable this feature:
 * 1. Implement backend /api/reports/generate endpoint
 * 2. Install and configure PDF generation library
 * 3. Update this service to call the backend API
 */

export type ReportType = 'ATTENDANCE' | 'GRADES' | 'PERFORMANCE' | 'COMBINED';

export interface ReportOptions {
  courseId: string;
  courseName: string;
  reportType: ReportType;
  startDate?: number;
  endDate?: number;
  includeCharts?: boolean;
}

export interface ReportData {
  courseName: string;
  generatedAt: number;
  generatedBy: string;
  students: Array<{
    studentId: string;
    studentName: string;
    attendancePercentage: number;
    averageGrade: number;
    assignmentsSubmitted: number;
    assignmentsTotal: number;
  }>;
  summary: {
    totalStudents: number;
    averageAttendance: number;
    averageGrade: number;
    atRiskCount: number;
  };
}

/**
 * Generate PDF Report
 * In production, this would use a library like react-native-pdf or send data to backend
 */
export const generatePDFReport = async (
  options: ReportOptions,
  data: ReportData,
): Promise<string> => {
  // Feature is disabled - fail explicitly
  const error = new Error(
    'PDF Report Generation is not yet implemented. This feature requires backend API support and PDF generation library.'
  );
  error.name = 'FEATURE_DISABLED';
  console.error('[PDFReport] Feature disabled:', error.message);
  throw error;
};

/**
 * Generate HTML content for PDF (helper function)
 */
const generateHTMLReport = (data: ReportData, options: ReportOptions): string => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #1e3a5f; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #1e3a5f; color: white; }
        .summary { margin-top: 20px; padding: 15px; background-color: #f4f6f9; }
      </style>
    </head>
    <body>
      <h1>${data.courseName} - ${options.reportType} Report</h1>
      <p>Generated: ${new Date(data.generatedAt).toLocaleString()}</p>
      <p>Generated by: ${data.generatedBy}</p>
      
      <div class="summary">
        <h2>Summary</h2>
        <p>Total Students: ${data.summary.totalStudents}</p>
        <p>Average Attendance: ${data.summary.averageAttendance}%</p>
        <p>Average Grade: ${data.summary.averageGrade}%</p>
        <p>At-Risk Students: ${data.summary.atRiskCount}</p>
      </div>
      
      <table>
        <thead>
          <tr>
            <th>Student Name</th>
            <th>Attendance %</th>
            <th>Average Grade</th>
            <th>Assignments</th>
          </tr>
        </thead>
        <tbody>
          ${data.students
            .map(
              student => `
            <tr>
              <td>${student.studentName}</td>
              <td>${student.attendancePercentage}%</td>
              <td>${student.averageGrade}%</td>
              <td>${student.assignmentsSubmitted}/${student.assignmentsTotal}</td>
            </tr>
          `,
            )
            .join('')}
        </tbody>
      </table>
    </body>
    </html>
  `;
};

/**
 * Share PDF Report
 */
export const sharePDFReport = async (filePath: string): Promise<void> => {
  try {
    // In production, use react-native-share or similar
    console.log('Sharing PDF report:', filePath);
    // await Share.open({url: `file://${filePath}`, type: 'application/pdf'});
  } catch (error) {
    console.error('Error sharing PDF report:', error);
    throw error;
  }
};

